### ISSUE TITLE
Importing the Correct/Incorrect icons fails

### ISSUE THREAD

**Issue by jameskraus** [jameskraus/jkchem#1]
Currently throws error for Correct/Incorrect markers on build

`ERROR in ./client/icons/incorrect.svg
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at Parser.exports.Parser.Parser.parseString (C:\Dropbox\Personal Projects\jkchem\node_modules\xml2js\lib\xml2js.js:497:18)
    at Parser.parseString (C:\Dropbox\Personal Projects\jkchem\node_modules\xml2js\lib\xml2js.js:7:59)
    at parseXml (C:\Dropbox\Personal Projects\jkchem\node_modules\svg-react-loader\index.js:23:15)
    at apply (C:\Dropbox\Personal Projects\jkchem\node_modules\lodash\_apply.js:15:25)
    at wrapper (C:\Dropbox\Personal Projects\jkchem\node_modules\lodash\_createPartial.js:38:12)
    at C:\Dropbox\Personal Projects\jkchem\node_modules\svg-react-loader\index.js:92:9
    at C:\Dropbox\Personal Projects\jkchem\node_modules\svg-react-loader\index.js:17:9
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
 @ ./client/components/RightWrongMarker/RightWrongMarker.js 17:17-53
`

Oddly, the header image loads fine, but these svgs fail. 

https://github.com/jameskraus/jkchem/blob/b2a7709e0bfe3db1e3cbc19f18b05a2c47c84292/client/components/RightWrongMarker/RightWrongMarker.js

**Comment by jameskraus** [comment]
Problem seems to be that file-loader was loading the .svg along with svg-react. By modifying the includes/excludes of those loaders, the problem seems to be solved. 

https://github.com/jameskraus/jkchem/commit/e84d3664d6a901a89e5b9a5a5aa5dd5b6b475921
